### PR TITLE
Add benchmark for Stdlib.Queue

### PR DESCRIPTION
**Pull request by Vincent-lau**
For comparsion between Saturn_lockfree Queue and Stdlib.Queue.

### CODE REVIEW

**Comment by polytypic** [comment]
Notice the "Stdlib benchmarks" link at the top of the README:

Screenshot 2024-09-06 at 18 35 32

**Comment by polytypic** [comment]
BTW, one reason the benchmarks do not use functors is that using functors pretty much prevents the native compiler from inlining.  Many of the lock-free data structure implementations have operations that use a worker-wrapper idiom where the wrapper is a trivial function designed to be inlined (often it just calls the recursive worker with an extra parameter or two).

**Comment by Vincent-lau** [comment]
Thanks! So does that mean that issue #56  is actually done by now? Or is there any further benchmarking work needed?

**Comment by polytypic** [comment]
I believe there is planty of benchmarking to be done.  However, it is a complex topic.  Most of the benchmarks we have are high contention benchmarks.  One idea would be to [add delays to simulate work](https://www.youtube.com/watch?v=7HBEXs48qmo&t=1862s).  Also, benchmarks that would exercise both read-only and read-write operations with various data structures could be interesting.

**Comment by Vincent-lau** [comment]
Ok, thanks. Closing this PR now since this work has already been done

**Pull request closed without merging**
