### PR TITLE
Add .nojekyll

### PR DESCRIPTION
**Pull request by lyrm**
Add `.nojekyll` file.

### CODE REVIEW

**Review by polytypic — APPROVED** [review]
🚀

**Comment by Sudha247** [comment]
I may be unfamiliar with this, but why do we need to bypass jekyll processing? Is it recommended for odoc generated files?

**Comment by lyrm** [comment]
It's a recommendation from @polytypic . Right now the documentation does not look good because (from what I understand) `jekyll` has issues with file names with `_` in it.

It is also how it is fixed in [eio](https://github.com/ocaml-multicore/eio/blob/gh-pages/.nojekyll).

**Comment by Sudha247** [comment]
Sounds good to me!

**Comment by polytypic** [comment]
Just noting that the CI failures should be unrelated to the addition of the `.nojekyll` file.

Also, I've added this `.nojekyll` thing to many repos already.

**Pull request merged**
